# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1604e86ba72fc1a2954c977f6d8ed274e31077f4576e8d3e8d63c4b99ee4ceebcd806d4ab90db057dee3844d14d7d91c0252dda67e08b61c7cb0845d55d8e16

test:
  secret_key_base: a507f88244c269fd7a7f6e31a212cd21c4c74eda6cc41a4e7b55d976c690852d31d3e4556fa58f3bab1e30f36e6cc187562cd058ba3653898d96dcf4e13e9db9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
